#!/bin/bash

build() {
    make -C build -j 16 install
}

case "${1:-build}" in
build)
    build
    ;;
py)
    build
    echo "Python test"
    time (cd dev && python3 -m unittest -v)
    ;;
cxx)
    build
    echo "Cxx test"
    time (cd dev && ./test)
    ;;
esac
