syntax = "proto3";

service EncoderService {
  rpc ExecuteBatchEncoderTask(Request) returns (Response);
}

service DecoderService {
  rpc ExecuteBatchDecoderTask(Request) returns (Response);
}

message LocalSharedTensor {
  bytes byte = 1;
  repeated int32 shape = 2;
  string dtype = 3;
}

message Data {
  string index = 1;
  string question = 2;
  string target = 3;
  string passages = 4;
  LocalSharedTensor scores = 5;
  LocalSharedTensor contexts = 6;
  LocalSharedTensor context_masks = 7;
  LocalSharedTensor tokens = 8;
  string text_ans = 9;
};

message Task {
  string env_type = 1;
  Data input = 2;
  Data output = 3;
};

message Request {
  repeated Task tasks = 1;
}

message Response {
  repeated Task tasks = 2;
}