# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from securerag.rpc import messages_pb2 as securerag_dot_rpc_dot_messages__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in securerag/rpc/messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncoderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteBatchEncoderTask = channel.unary_unary(
                '/EncoderService/ExecuteBatchEncoderTask',
                request_serializer=securerag_dot_rpc_dot_messages__pb2.Request.SerializeToString,
                response_deserializer=securerag_dot_rpc_dot_messages__pb2.Response.FromString,
                _registered_method=True)


class EncoderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteBatchEncoderTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteBatchEncoderTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBatchEncoderTask,
                    request_deserializer=securerag_dot_rpc_dot_messages__pb2.Request.FromString,
                    response_serializer=securerag_dot_rpc_dot_messages__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EncoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EncoderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncoderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteBatchEncoderTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EncoderService/ExecuteBatchEncoderTask',
            securerag_dot_rpc_dot_messages__pb2.Request.SerializeToString,
            securerag_dot_rpc_dot_messages__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecoderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteBatchDecoderTask = channel.unary_unary(
                '/DecoderService/ExecuteBatchDecoderTask',
                request_serializer=securerag_dot_rpc_dot_messages__pb2.Request.SerializeToString,
                response_deserializer=securerag_dot_rpc_dot_messages__pb2.Response.FromString,
                _registered_method=True)


class DecoderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteBatchDecoderTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteBatchDecoderTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBatchDecoderTask,
                    request_deserializer=securerag_dot_rpc_dot_messages__pb2.Request.FromString,
                    response_serializer=securerag_dot_rpc_dot_messages__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DecoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DecoderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecoderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteBatchDecoderTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DecoderService/ExecuteBatchDecoderTask',
            securerag_dot_rpc_dot_messages__pb2.Request.SerializeToString,
            securerag_dot_rpc_dot_messages__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
